import type { BrandPublic } from "@/lib/brand/server";
import type { EmailProvider, SendEmailResult } from "@/lib/email/emailProvider";
import { getDictionary } from "@/lib/i18n/dictionaries";
import { fillTemplate } from "@/lib/i18n/fillTemplate";

/**
 * Escape user-provided values before interpolating into the email HTML so a
 * crafted address cannot inject markup or break attributes.
 */
function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export interface SendPasswordResetEmailParams {
  to: string;
  /** Absolute action link generated by `auth.admin.generateLink({ type: "recovery" })`. */
  resetLink: string;
  brand: BrandPublic;
  locale: string;
  emailProvider: EmailProvider;
}

/**
 * Compose and dispatch the password reset email. Brand and copy come from the
 * project sources of truth (`system.properties` + dictionaries) so a rebrand
 * or translation change reaches users without code changes here.
 */
export async function sendPasswordResetEmail(
  params: SendPasswordResetEmailParams,
): Promise<SendEmailResult> {
  const dict = await getDictionary(params.locale);
  const t = dict.emailPasswordReset;
  const subject = fillTemplate(t.subject, { brandName: params.brand.name });
  const html = fillTemplate(t.html, {
    brandName: escapeHtml(params.brand.name),
    email: escapeHtml(params.to),
    href: escapeHtml(params.resetLink),
  });
  return params.emailProvider.sendEmail({ to: params.to, subject, html });
}
