import type { BotMatcher } from "./userAgentBotTypes";

/**
 * Social network link previews + operational bots (SEO crawlers, uptime
 * monitors, security scanners, generic feed fetchers). Listed after the
 * search/AI bots in the combined directory because their tokens are usually
 * less specific.
 */
export const SOCIAL_OPS_BOTS: BotMatcher[] = [
  {
    token: "facebookexternalhit",
    label: "Facebook link preview",
    vendor: "Meta",
    vendorUrl: "https://developers.facebook.com/docs/sharing/webmasters/crawler",
    category: "social",
  },
  {
    token: "facebookcatalog",
    label: "Facebook Catalog",
    vendor: "Meta",
    vendorUrl: "https://developers.facebook.com/docs/marketing-api/catalog/reference",
    category: "social",
  },
  {
    token: "meta-externalagent",
    label: "Meta external agent",
    vendor: "Meta",
    vendorUrl: "https://developers.facebook.com/docs/sharing/webmasters/crawler",
    category: "social",
  },
  {
    token: "WhatsApp",
    label: "WhatsApp link preview",
    vendor: "Meta",
    vendorUrl: "https://faq.whatsapp.com/",
    category: "preview",
  },
  {
    token: "Instagram",
    label: "Instagram",
    vendor: "Meta",
    vendorUrl: "https://help.instagram.com/",
    category: "social",
  },
  {
    token: "Twitterbot",
    label: "Twitter / X link preview",
    vendor: "X",
    vendorUrl: "https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started",
    category: "social",
  },
  {
    token: "LinkedInBot",
    label: "LinkedIn link preview",
    vendor: "LinkedIn",
    vendorUrl: "https://www.linkedin.com/help/linkedin/answer/95603",
    category: "social",
  },
  {
    token: "Slackbot",
    label: "Slack unfurl",
    vendor: "Slack",
    vendorUrl: "https://api.slack.com/robots",
    category: "preview",
  },
  {
    token: "Slack-ImgProxy",
    label: "Slack image proxy",
    vendor: "Slack",
    vendorUrl: "https://api.slack.com/robots",
    category: "preview",
  },
  {
    token: "TelegramBot",
    label: "Telegram link preview",
    vendor: "Telegram",
    vendorUrl: "https://core.telegram.org/bots/webapps",
    category: "preview",
  },
  {
    token: "Discordbot",
    label: "Discord link preview",
    vendor: "Discord",
    vendorUrl: "https://discord.com/safety",
    category: "preview",
  },
  {
    token: "Pinterest",
    label: "Pinterest",
    vendor: "Pinterest",
    vendorUrl: "https://help.pinterest.com/",
    category: "social",
  },
  {
    token: "redditbot",
    label: "Reddit",
    vendor: "Reddit",
    vendorUrl: "https://support.reddithelp.com/",
    category: "social",
  },
  {
    token: "TikTokSpider",
    label: "TikTok",
    vendor: "ByteDance",
    vendorUrl: "https://www.tiktok.com/",
    category: "social",
  },
  {
    token: "AhrefsBot",
    label: "Ahrefs",
    vendor: "Ahrefs",
    vendorUrl: "https://ahrefs.com/robot",
    category: "seo",
  },
  {
    token: "SemrushBot",
    label: "SEMrush",
    vendor: "SEMrush",
    vendorUrl: "https://www.semrush.com/bot/",
    category: "seo",
  },
  {
    token: "MJ12bot",
    label: "Majestic",
    vendor: "Majestic",
    vendorUrl: "https://mj12bot.com/",
    category: "seo",
  },
  {
    token: "DotBot",
    label: "Moz DotBot",
    vendor: "Moz",
    vendorUrl: "https://moz.com/help/moz-procedures/crawlers/dotbot",
    category: "seo",
  },
  {
    token: "rogerbot",
    label: "Moz rogerbot",
    vendor: "Moz",
    vendorUrl: "https://moz.com/help/moz-procedures/crawlers/rogerbot",
    category: "seo",
  },
  {
    token: "BLEXBot",
    label: "BLEXBot",
    vendor: "WebMeUp",
    vendorUrl: "http://webmeup-crawler.com/",
    category: "seo",
  },
  {
    token: "SeekportBot",
    label: "Seekport",
    vendor: "Seekport",
    vendorUrl: "https://bot.seekport.com",
    category: "seo",
  },
  {
    token: "UptimeRobot",
    label: "UptimeRobot",
    vendor: "UptimeRobot",
    vendorUrl: "https://uptimerobot.com/",
    category: "monitor",
  },
  {
    token: "Pingdom",
    label: "Pingdom",
    vendor: "Pingdom",
    vendorUrl: "https://www.pingdom.com/",
    category: "monitor",
  },
  {
    token: "BetterUptime",
    label: "Better Uptime",
    vendor: "Better Stack",
    vendorUrl: "https://betterstack.com/uptime",
    category: "monitor",
  },
  {
    token: "StatusCake",
    label: "StatusCake",
    vendor: "StatusCake",
    vendorUrl: "https://www.statuscake.com/",
    category: "monitor",
  },
  {
    token: "site24x7",
    label: "Site24x7",
    vendor: "Zoho",
    vendorUrl: "https://www.site24x7.com/",
    category: "monitor",
  },
  {
    token: "GoogleSites",
    label: "Google Sites",
    vendor: "Google",
    vendorUrl: "https://sites.google.com/",
    category: "generic",
  },
  {
    token: "Feedly",
    label: "Feedly",
    vendor: "Feedly",
    vendorUrl: "https://developer.feedly.com/",
    category: "feed",
  },
  {
    token: "Inoreader",
    label: "Inoreader",
    vendor: "Inoreader",
    vendorUrl: "https://www.inoreader.com/",
    category: "feed",
  },
  {
    token: "NetcraftSurveyAgent",
    label: "Netcraft",
    vendor: "Netcraft",
    vendorUrl: "https://www.netcraft.com/",
    category: "security",
  },
  {
    token: "Censys",
    label: "Censys",
    vendor: "Censys",
    vendorUrl: "https://about.censys.io/",
    category: "security",
  },
  {
    token: "Expanse",
    label: "Expanse / Palo Alto",
    vendor: "Palo Alto Networks",
    vendorUrl: "https://www.paloaltonetworks.com/cortex/cortex-xpanse",
    category: "security",
  },
  {
    token: "ZoominfoBot",
    label: "ZoomInfo",
    vendor: "ZoomInfo",
    vendorUrl: "https://www.zoominfo.com/about-zoominfo/contact-zoominfo",
    category: "generic",
  },
  {
    token: "Vercelbot",
    label: "Vercel bot",
    vendor: "Vercel",
    vendorUrl: "https://vercel.com/docs",
    category: "generic",
  },
];
