/**
 * Maps `supabase status -o env` style KEY=VALUE lines into `.env.local.e2e` fields.
 * Pure — no fs / network. Used by `scripts/e2e-stack-up.mjs`.
 */

import { E2E_TOUR_RECEIPT_FIXTURE } from "./tourReceiptFixture";

export type E2eStackSeedCreds = {
  adminEmail: string;
  adminPassword: string;
  studentEmail?: string;
  parentEmail?: string;
  teacherEmail?: string;
  sharedPassword?: string;
  locale?: string;
  appPort?: number;
  cohortId?: string;
  sectionId?: string;
  studentId?: string;
};

const DEFAULT_SEED: Required<
  Pick<
    E2eStackSeedCreds,
    | "adminEmail"
    | "adminPassword"
    | "studentEmail"
    | "parentEmail"
    | "teacherEmail"
    | "sharedPassword"
    | "locale"
    | "appPort"
  >
> = {
  adminEmail: "e2e-admin@example.test",
  adminPassword: "E2eLocal!Stack1",
  studentEmail: "e2e-student@example.test",
  parentEmail: "e2e-parent@example.test",
  teacherEmail: "e2e-teacher@example.test",
  sharedPassword: "E2eLocal!Stack1",
  locale: "es",
  appPort: 3100,
};

/** Parse dotenv / `supabase status -o env` output. */
export function parseStatusEnv(raw: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

/**
 * Build the body of `.env.local.e2e` from local `supabase status` env.
 * Accepts either exported names (API_URL, ANON_KEY, …) or already-prefixed NEXT_PUBLIC_*.
 */
export function buildE2eLocalEnvFileContents(
  statusEnv: Record<string, string>,
  seed: Partial<E2eStackSeedCreds> = {},
): string {
  const s = { ...DEFAULT_SEED, ...seed };
  const apiUrl =
    statusEnv.API_URL?.trim() ||
    statusEnv.NEXT_PUBLIC_SUPABASE_URL?.trim() ||
    statusEnv.SUPABASE_URL?.trim() ||
    "";
  const anon =
    statusEnv.ANON_KEY?.trim() ||
    statusEnv.NEXT_PUBLIC_SUPABASE_ANON_KEY?.trim() ||
    statusEnv.SUPABASE_ANON_KEY?.trim() ||
    "";
  const service =
    statusEnv.SERVICE_ROLE_KEY?.trim() ||
    statusEnv.SUPABASE_SERVICE_ROLE_KEY?.trim() ||
    "";
  const dbUrl =
    statusEnv.DB_URL?.trim() ||
    statusEnv.DATABASE_URL?.trim() ||
    "";

  if (!apiUrl || !anon || !service) {
    throw new Error(
      "Local supabase status missing API_URL / ANON_KEY / SERVICE_ROLE_KEY (or NEXT_PUBLIC_/SUPABASE_ equivalents)",
    );
  }

  const appUrl = `http://127.0.0.1:${s.appPort}`;
  const lines = [
    "# Generated by scripts/e2e-stack-up.mjs — isolated local Supabase (not nago/golden).",
    "# Do not commit. Regenerate with: npm run e2e:stack:up",
    "",
    `NEXT_PUBLIC_SUPABASE_URL=${apiUrl}`,
    `NEXT_PUBLIC_SUPABASE_ANON_KEY=${anon}`,
    `SUPABASE_SERVICE_ROLE_KEY=${service}`,
    dbUrl ? `DATABASE_URL=${dbUrl}` : "# DATABASE_URL=",
    "",
    `NEXT_PUBLIC_APP_URL=${appUrl}`,
    "SKIP_INITIAL_SITE_SETUP=1",
    "",
    "E2E_STACK=isolated",
    "GE_DEV_TARGET=e2e",
    "# Outbound mail: RecordingEmailProvider — never call Resend from the e2e Next process.",
    "EMAIL_PROVIDER=recording",
    `E2E_ADMIN_EMAIL=${s.adminEmail}`,
    `E2E_ADMIN_PASSWORD=${s.adminPassword}`,
    `E2E_STUDENT_EMAIL=${s.studentEmail}`,
    `E2E_PARENT_EMAIL=${s.parentEmail}`,
    `E2E_TEACHER_EMAIL=${s.teacherEmail}`,
    `E2E_USER_PASSWORD=${s.sharedPassword}`,
    `E2E_LOCALE=${s.locale}`,
    `E2E_PORT=${s.appPort}`,
    `PLAYWRIGHT_BASE_URL=${appUrl}`,
  ];
  if (s.cohortId?.trim()) {
    lines.push(`E2E_COHORT_ID=${s.cohortId.trim()}`);
  }
  if (s.sectionId?.trim()) {
    lines.push(`E2E_SECTION_ID=${s.sectionId.trim()}`);
  }
  if (s.studentId?.trim()) {
    lines.push(`E2E_STUDENT_ID=${s.studentId.trim()}`);
  }
  lines.push(`E2E_RECEIPT_ID=${E2E_TOUR_RECEIPT_FIXTURE.receiptId}`);
  lines.push("");
  return lines.join("\n");
}

export { DEFAULT_SEED as E2E_LOCAL_DEFAULT_SEED };

