import type { LandingSectionSlug } from "@/types/theming";

/**
 * Editable copy + media slots for the `nago` (Capoeira Nagô) landing shell.
 * Dict paths live under `dict.landing.nago.*`.
 */
export const NAGO_LANDING_COPY_KEYS_BY_SECTION: Readonly<
  Record<LandingSectionSlug, ReadonlyArray<string>>
> = {
  inicio: [
    "nago.chrome.openMenu",
    "nago.chrome.closeMenu",
    "nago.chrome.facebookAria",
    "nago.chrome.instagramAria",
    "nago.chrome.youtubeAria",
    "nago.chrome.whatsappAria",
    "nago.chrome.soundOn",
    "nago.chrome.soundOff",
    "nago.nav.inicio",
    "nago.nav.clases",
    "nago.nav.horarios",
    "nago.nav.nago",
    "nago.nav.galeria",
    "nago.nav.eventos",
    "nago.nav.contacto",
    "nago.nav.agendaCta",
    "nago.register.shellTitle",
    "nago.register.shellLead",
    "nago.hero.title",
    "nago.hero.titleAccent",
    "nago.hero.subtitle",
    "nago.hero.subtitleTrail",
    "nago.hero.tagline",
    "nago.hero.ctaPrimary",
    "nago.hero.ctaSecondary",
    "nago.hero.discover",
    "nago.hero.slidePrev",
    "nago.hero.slideNext",
    "nago.hero.slideGoTo",
  ],
  historia: [
    "nago.experiencia.title",
    "nago.experiencia.body",
    "nago.experiencia.deporte",
    "nago.experiencia.movimiento",
    "nago.experiencia.disciplina",
    "nago.experiencia.musica",
    "nago.experiencia.cultura",
    "nago.experiencia.desarrollo",
    "nago.mestre.kicker",
    "nago.mestre.title",
    "nago.mestre.body",
    "nago.mestre.cta",
    "nago.mestre.years",
    "nago.mestre.yearsLabel",
    "nago.mestre.students",
    "nago.mestre.studentsLabel",
    "nago.mestre.events",
    "nago.mestre.eventsLabel",
    "nago.mestre.chile",
    "nago.mestre.chileLabel",
  ],
  oferta: [
    "nago.pilares.deporte.title",
    "nago.pilares.deporte.body",
    "nago.pilares.disciplina.title",
    "nago.pilares.disciplina.body",
    "nago.pilares.confianza.title",
    "nago.pilares.confianza.body",
    "nago.pilares.cultura.title",
    "nago.pilares.cultura.body",
    "nago.pilares.superacion.title",
    "nago.pilares.superacion.body",
    "nago.programas.kicker",
    "nago.programas.sectionTitle",
    "nago.programas.lead",
    "nago.programas.ctaHorarios",
    "nago.programas.verClases",
    "nago.programas.noExperience",
    "nago.programas.ninos.title",
    "nago.programas.ninos.ages",
    "nago.programas.ninos.body",
    "nago.programas.jovenes.title",
    "nago.programas.jovenes.ages",
    "nago.programas.jovenes.body",
    "nago.programas.adultos.title",
    "nago.programas.adultos.ages",
    "nago.programas.adultos.body",
    "nago.programas.mayores.title",
    "nago.programas.mayores.ages",
    "nago.programas.mayores.body",
  ],
  modalidades: [
    "nago.accion.sectionTitle",
    "nago.galeria.sectionTitle",
    "nago.galeria.verMas",
    "nago.testimonios.sectionTitle",
    "nago.testimonios.t1.quote",
    "nago.testimonios.t1.role",
    "nago.testimonios.t2.quote",
    "nago.testimonios.t2.role",
    "nago.testimonios.t3.quote",
    "nago.testimonios.t3.role",
  ],
  niveles: [
    "nago.horarios.sectionTitle",
    "nago.horarios.lead",
    "nago.horarios.venue",
    "nago.horarios.note",
    "nago.horarios.cta",
    "nago.horarios.pricesTitle",
    "nago.horarios.timesOne",
    "nago.horarios.timesMany",
    "nago.horarios.trialKicker",
    "nago.horarios.trial",
    "nago.horarios.familyKicker",
    "nago.horarios.family",
    "nago.horarios.baby.title",
    "nago.horarios.baby.ages",
    "nago.horarios.baby.slots",
    "nago.horarios.kids47.title",
    "nago.horarios.kids47.ages",
    "nago.horarios.kids47.slots",
    "nago.horarios.kids810.title",
    "nago.horarios.kids810.ages",
    "nago.horarios.kids810.slots",
    "nago.horarios.teens.title",
    "nago.horarios.teens.ages",
    "nago.horarios.teens.slots",
    "nago.horarios.mixta.title",
    "nago.horarios.mixta.ages",
    "nago.horarios.mixta.slots",
    "nago.horarios.adultos.title",
    "nago.horarios.adultos.ages",
    "nago.horarios.adultos.slots",
    "nago.horarios.mayores.title",
    "nago.horarios.mayores.ages",
    "nago.horarios.mayores.slots",
    "nago.horarios.mayores.note",
  ],
  certificaciones: [
    "nago.eventosHome.sectionTitle",
    "nago.eventosHome.lead",
    "nago.eventosHome.viewAll",
    "nago.cta.title",
    "nago.cta.subtitle",
    "nago.cta.button",
    "nago.cta.whatsapp",
    "nago.lead.name",
    "nago.lead.whatsapp",
    "nago.lead.age",
    "nago.lead.program",
    "nago.lead.message",
    "nago.lead.submit",
    "nago.footer.enlacesTitle",
    "nago.footer.siguenos",
    "nago.footer.rightsLine",
    "nago.footer.location",
    "nago.contact.title",
    "nago.contact.phoneDisplay",
    "nago.contact.instagramUrl",
    "nago.contact.facebookUrl",
    "nago.contact.whatsappUrl",
    "nago.contact.youtubeUrl",
  ],
};

export const NAGO_MEDIA_SLOTS_BY_SECTION: Readonly<
  Record<LandingSectionSlug, number>
> = {
  inicio: 2,
  historia: 1,
  modalidades: 3,
  niveles: 0,
  certificaciones: 0,
  oferta: 4,
};

export const NAGO_EDITABLE_COPY_KEYS: ReadonlyArray<string> = Object.values(
  NAGO_LANDING_COPY_KEYS_BY_SECTION,
).flat();
