-- Golden English — tema explícito alineado con system.properties del repo.
-- Idempotente: ON CONFLICT (slug) actualiza propiedades visibles para CMS/runtime.

INSERT INTO public.site_themes (
  slug,
  name,
  is_active,
  template_kind,
  properties,
  content,
  blocks,
  is_system_default
)
VALUES (
  'golden-english',
  'Golden English',
  FALSE,
  'classic'::public.site_theme_kind,
  jsonb_build_object(
    'app.name', 'Golden English',
    'app.legal.name', 'Instituto de Lenguas Golden English',
    'app.tagline', 'Más de 20 años enseñando inglés, creando oportunidades',
    'app.tagline.en', 'Over 20 years teaching English, creating opportunities',
    'app.legal.registry', 'Resolución 1297/05 - Ministerio de Educación, Formosa',
    'app.logo.path', '/images/logo.png',
    'app.logo.alt', 'Logo GE Golden English',
    'app.favicon.path', '/favicon_io/favicon.ico',
    'color.primary', '#103A5C',
    'color.primary.light', '#2A5B84',
    'color.primary.dark', '#0A253D',
    'color.primary.foreground', '#FFFFFF',
    'color.secondary', '#A31A22',
    'color.secondary.light', '#D43D46',
    'color.secondary.dark', '#730F15',
    'color.secondary.foreground', '#FFFFFF',
    'color.accent', '#F0B932',
    'color.accent.foreground', '#0F1F33',
    'color.background', '#FAF9F6',
    'color.surface', '#FFFFFF',
    'color.foreground', '#103A5C',
    'color.muted', '#F0EFEA',
    'color.muted.foreground', '#5C6B7A',
    'color.border', '#E2E0D8',
    'color.success', '#16A34A',
    'color.warning', '#EAB308',
    'color.error', '#DC2626',
    'color.info', '#2563EB',
    'color.calendarSpecial.holiday', '#374151',
    'color.calendarSpecial.institutionalExam', '#991B1B',
    'color.calendarSpecial.parentMeeting', '#6D28D9',
    'color.calendarSpecial.social', '#166534',
    'color.calendarSpecial.trimesterAdmin', '#1E40AF',
    'shadow.soft', '0 4px 24px -4px rgb(16 58 92 / 12%)',
    'shadow.card', '0 12px 40px -12px rgb(16 58 92 / 18%)',
    'layout.max.width', '1280px',
    'layout.border.radius', '0.75rem',
    'contact.email', 'crisins@hotmail.com',
    'contact.phone', '+54 9 3718 528-383 ',
    'contact.address', 'Riacho He Hé, Provincia de Formosa, Argentina',
    'social.facebook', 'https://www.facebook.com/Lateachergolden',
    'social.instagram', 'https://www.instagram.com/goldenenglishok/',
    'social.whatsapp', 'https://wa.me/5493718528383'
  ),
  '{}'::jsonb,
  '[]'::jsonb,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  is_active = EXCLUDED.is_active,
  template_kind = EXCLUDED.template_kind,
  properties = EXCLUDED.properties,
  content = EXCLUDED.content,
  blocks = EXCLUDED.blocks,
  updated_at = now();
