/** Returned by messaging use cases — map to copy in server actions via `mapMessagingUseCaseCode`. */
export const MESSAGING_UC_NO_TEACHER = "MESSAGING_UC_NO_TEACHER";
export const MESSAGING_UC_PERSIST_FAILED = "MESSAGING_UC_PERSIST_FAILED";
export const MESSAGING_UC_REPLY_NOT_FOUND = "MESSAGING_UC_REPLY_NOT_FOUND";
export const MESSAGING_UC_REPLY_INVALID_SENDER = "MESSAGING_UC_REPLY_INVALID_SENDER";
export const MESSAGING_UC_INVALID_RECIPIENT = "MESSAGING_UC_INVALID_RECIPIENT";
