import type { ContentOnlyStepDef } from "@/lib/admin-tutorials/explainContentOnlyTour";
import { ADMIN_TOUR_ANCHORS } from "@/lib/admin-tutorials/selectors";

/** Content-only defs for users, registrations, events, finance, messages. */
export const SCREEN_TOUR_DEFS_PEOPLE_FINANCE = {
  "admin-users": [
    { key: "intro", anchor: null },
    { key: "subnav", anchor: ADMIN_TOUR_ANCHORS.usersSubnav, optional: true },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.usersTitle },
    { key: "toolbar", anchor: ADMIN_TOUR_ANCHORS.usersToolbar },
    { key: "table", anchor: ADMIN_TOUR_ANCHORS.usersTable },
    { key: "closing", anchor: null },
  ],
  "admin-users-new": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.usersNewTitle },
    { key: "form", anchor: ADMIN_TOUR_ANCHORS.createUserForm },
    { key: "role", anchor: ADMIN_TOUR_ANCHORS.createUserRole },
    { key: "credentials", anchor: ADMIN_TOUR_ANCHORS.createUserPassword },
    { key: "guardian", anchor: ADMIN_TOUR_ANCHORS.createUserGuardian, optional: true },
    { key: "submit", anchor: ADMIN_TOUR_ANCHORS.createUserSubmit },
    { key: "closing", anchor: null },
  ],
  "admin-users-import": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.usersImportTitle },
    { key: "chooseFile", anchor: ADMIN_TOUR_ANCHORS.usersImportChooseFile },
    { key: "closing", anchor: null },
  ],
  "admin-user-detail": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.userDetailTitle },
    { key: "tabsIntro", anchor: ADMIN_TOUR_ANCHORS.userDetailTabs },
    { key: "tabSummary", anchor: ADMIN_TOUR_ANCHORS.userDetailTabSummary },
    { key: "tabAcademic", anchor: ADMIN_TOUR_ANCHORS.userDetailTabAcademic },
    { key: "tabPayments", anchor: ADMIN_TOUR_ANCHORS.userDetailTabPayments, optional: true },
    { key: "tabFamily", anchor: ADMIN_TOUR_ANCHORS.userDetailTabFamily, optional: true },
    { key: "tabSecurity", anchor: ADMIN_TOUR_ANCHORS.userDetailSecurityTab },
    { key: "closing", anchor: null },
  ],
  "admin-user-billing": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.userBillingTitle },
    { key: "tabsIntro", anchor: ADMIN_TOUR_ANCHORS.userBillingTabs },
    { key: "tabHistory", anchor: ADMIN_TOUR_ANCHORS.userBillingTabHistory },
    { key: "tabScholarships", anchor: ADMIN_TOUR_ANCHORS.scholarshipTab },
    { key: "tabEnrollment", anchor: ADMIN_TOUR_ANCHORS.userBillingTabEnrollment },
    { key: "closing", anchor: null },
  ],
  "admin-registrations": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.registrationsTitle },
    { key: "toolbar", anchor: ADMIN_TOUR_ANCHORS.registrationsToolbar },
    { key: "table", anchor: ADMIN_TOUR_ANCHORS.registrationsTable },
    { key: "closing", anchor: null },
  ],
  "admin-events": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.eventsTitle },
    { key: "kpis", anchor: ADMIN_TOUR_ANCHORS.eventsKpis, optional: true },
    { key: "createCta", anchor: ADMIN_TOUR_ANCHORS.eventsCreateCta },
    { key: "table", anchor: ADMIN_TOUR_ANCHORS.eventsTable },
    { key: "closing", anchor: null },
  ],
  "admin-events-new": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.eventsNewTitle },
    { key: "form", anchor: ADMIN_TOUR_ANCHORS.eventCreateForm },
    { key: "schedule", anchor: ADMIN_TOUR_ANCHORS.eventCreateDate },
    { key: "pricing", anchor: ADMIN_TOUR_ANCHORS.eventCreatePricing },
    { key: "submit", anchor: ADMIN_TOUR_ANCHORS.eventCreateSubmit },
    { key: "closing", anchor: null },
  ],
  "admin-event-detail": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.eventDetailTitle },
    { key: "tabsIntro", anchor: ADMIN_TOUR_ANCHORS.eventDetailTabs },
    { key: "tabSummary", anchor: ADMIN_TOUR_ANCHORS.eventDetailTabSummary },
    { key: "tabForm", anchor: ADMIN_TOUR_ANCHORS.eventDetailTabForm },
    { key: "tabAttendees", anchor: ADMIN_TOUR_ANCHORS.eventDetailTabAttendees },
    { key: "tabPayments", anchor: ADMIN_TOUR_ANCHORS.eventPaymentsTab },
    { key: "tabWaitlist", anchor: ADMIN_TOUR_ANCHORS.eventDetailTabWaitlist },
    { key: "tabNotifications", anchor: ADMIN_TOUR_ANCHORS.eventDetailTabNotifications },
    { key: "publish", anchor: ADMIN_TOUR_ANCHORS.eventDetailPublish, optional: true },
    { key: "closing", anchor: null },
  ],
  "admin-finance": [
    { key: "intro", anchor: null },
    { key: "header", anchor: ADMIN_TOUR_ANCHORS.financeHeader },
    { key: "tabsIntro", anchor: ADMIN_TOUR_ANCHORS.financeTabs },
    { key: "tabCollections", anchor: ADMIN_TOUR_ANCHORS.financeTabCollections },
    { key: "tabInbox", anchor: ADMIN_TOUR_ANCHORS.financeTabInbox },
    { key: "tabEvents", anchor: ADMIN_TOUR_ANCHORS.financeTabEvents },
    { key: "tabInsights", anchor: ADMIN_TOUR_ANCHORS.financeTabInsights },
    { key: "tabSettings", anchor: ADMIN_TOUR_ANCHORS.financeTabSettings },
    { key: "cohortYear", anchor: ADMIN_TOUR_ANCHORS.financeCohortYear, optional: true },
    { key: "closing", anchor: null },
  ],
  "admin-messages": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.messagesTitle },
    { key: "composeCta", anchor: ADMIN_TOUR_ANCHORS.messagesComposeCta },
    { key: "tabsIntro", anchor: ADMIN_TOUR_ANCHORS.messagesTabs },
    { key: "tabInbox", anchor: ADMIN_TOUR_ANCHORS.messagesTabInbox },
    { key: "tabSent", anchor: ADMIN_TOUR_ANCHORS.messagesTabSent },
    { key: "list", anchor: ADMIN_TOUR_ANCHORS.messagesList },
    { key: "closing", anchor: null },
  ],
  "admin-messages-compose": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.messagesComposeTitle },
    { key: "recipient", anchor: ADMIN_TOUR_ANCHORS.messagesComposeRecipient },
    { key: "body", anchor: ADMIN_TOUR_ANCHORS.messagesComposeBody },
    { key: "send", anchor: ADMIN_TOUR_ANCHORS.messagesComposeSend },
    { key: "closing", anchor: null },
  ],
  "admin-message-detail": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.messagesDetailTitle },
    { key: "participants", anchor: ADMIN_TOUR_ANCHORS.messagesDetailParticipants },
    { key: "body", anchor: ADMIN_TOUR_ANCHORS.messagesDetailBody },
    { key: "actions", anchor: ADMIN_TOUR_ANCHORS.messagesDetailActions },
    { key: "closing", anchor: null },
  ],
  "admin-finance-collections-section": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.sectionCollectionsTitle },
    { key: "tabsIntro", anchor: ADMIN_TOUR_ANCHORS.sectionCollectionsTabs },
    { key: "tabMatrix", anchor: ADMIN_TOUR_ANCHORS.sectionCollectionsTabMatrix },
    { key: "tabSettings", anchor: ADMIN_TOUR_ANCHORS.sectionCollectionsTabSettings },
    { key: "tabHistory", anchor: ADMIN_TOUR_ANCHORS.sectionCollectionsTabHistory },
    { key: "tabScholarships", anchor: ADMIN_TOUR_ANCHORS.sectionCollectionsScholarshipsTab },
    { key: "tabEnrollment", anchor: ADMIN_TOUR_ANCHORS.sectionCollectionsTabEnrollment },
    { key: "closing", anchor: null },
  ],
  "admin-finance-receipt-detail": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.financeReceiptDetailTitle },
    { key: "preview", anchor: ADMIN_TOUR_ANCHORS.financeReceiptDetailPreview },
    { key: "actions", anchor: ADMIN_TOUR_ANCHORS.financeReceiptDetailActions },
    { key: "closing", anchor: null },
  ],
} as const satisfies Record<string, readonly ContentOnlyStepDef[]>;
