import type { ContentOnlyStepDef } from "@/lib/admin-tutorials/explainContentOnlyTour";
import { ADMIN_TOUR_ANCHORS } from "@/lib/admin-tutorials/selectors";

/** Content-only defs for academic, CMS, settings, profile. */
export const SCREEN_TOUR_DEFS_ACADEMIC_CMS = {
  "admin-academic": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.academicTitle },
    { key: "newCohort", anchor: ADMIN_TOUR_ANCHORS.newCohort },
    { key: "boardTabs", anchor: ADMIN_TOUR_ANCHORS.academicBoardTabs },
    { key: "cohortList", anchor: ADMIN_TOUR_ANCHORS.academicCohortList },
    { key: "closing", anchor: null },
  ],
  "admin-cohort-detail": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.cohortDetailTitle },
    { key: "tabsIntro", anchor: ADMIN_TOUR_ANCHORS.cohortDetailTabs },
    { key: "tabOverview", anchor: ADMIN_TOUR_ANCHORS.cohortDetailTabOverview },
    { key: "tabSections", anchor: ADMIN_TOUR_ANCHORS.cohortSectionsTab },
    { key: "tabRetention", anchor: ADMIN_TOUR_ANCHORS.cohortDetailTabRetention },
    { key: "tabTransfers", anchor: ADMIN_TOUR_ANCHORS.cohortDetailTabTransfers },
    { key: "closing", anchor: null },
  ],
  "admin-section-attendance": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.sectionAttendanceTitle },
    { key: "workspace", anchor: ADMIN_TOUR_ANCHORS.sectionAttendanceRoot },
    { key: "matrix", anchor: ADMIN_TOUR_ANCHORS.sectionAttendanceMatrix, optional: true },
    { key: "closing", anchor: null },
  ],
  "admin-section-detail": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.sectionDetailTitle },
    { key: "hubAreas", anchor: ADMIN_TOUR_ANCHORS.sectionDetailTabs },
    { key: "hubOverview", anchor: ADMIN_TOUR_ANCHORS.sectionDetail },
    { key: "closing", anchor: null },
  ],
  "admin-calendar": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.calendarTitle },
    { key: "filters", anchor: ADMIN_TOUR_ANCHORS.calendarFilters, optional: true },
    { key: "schedule", anchor: ADMIN_TOUR_ANCHORS.calendarSchedule },
    { key: "closing", anchor: null },
  ],
  "admin-contents": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.contentsTitle },
    { key: "tabsIntro", anchor: ADMIN_TOUR_ANCHORS.contentsTabs },
    { key: "tabRepository", anchor: ADMIN_TOUR_ANCHORS.contentsTabRepository },
    { key: "tabRoutes", anchor: ADMIN_TOUR_ANCHORS.contentsTabRoutes },
    { key: "closing", anchor: null },
  ],
  "admin-badges": [
    { key: "intro", anchor: null },
    { key: "header", anchor: ADMIN_TOUR_ANCHORS.badgesHeader },
    { key: "createCta", anchor: ADMIN_TOUR_ANCHORS.badgesCreateCta },
    { key: "categoryTabs", anchor: ADMIN_TOUR_ANCHORS.badgesCategoryTabs },
    { key: "table", anchor: ADMIN_TOUR_ANCHORS.badgesTable },
    { key: "closing", anchor: null },
  ],
  "admin-coupons": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.couponsTitle },
    { key: "createForm", anchor: ADMIN_TOUR_ANCHORS.couponsCreateForm },
    { key: "table", anchor: ADMIN_TOUR_ANCHORS.couponsTable },
    { key: "closing", anchor: null },
  ],
  "admin-promotions": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.promotionsTitle },
    { key: "createForm", anchor: ADMIN_TOUR_ANCHORS.promotionsCreateForm },
    { key: "table", anchor: ADMIN_TOUR_ANCHORS.promotionsTable },
    { key: "closing", anchor: null },
  ],
  "admin-email-templates": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.emailTemplatesTitle },
    { key: "select", anchor: ADMIN_TOUR_ANCHORS.emailTemplatesSelect },
    { key: "editor", anchor: ADMIN_TOUR_ANCHORS.emailTemplatesEditor },
    { key: "preview", anchor: ADMIN_TOUR_ANCHORS.emailTemplatesPreview },
    { key: "closing", anchor: null },
  ],
  "admin-blog": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.blogTitle },
    { key: "createCta", anchor: ADMIN_TOUR_ANCHORS.blogCreateCta },
    { key: "articleList", anchor: ADMIN_TOUR_ANCHORS.blogArticleList },
    { key: "closing", anchor: null },
  ],
  "admin-blog-new": [
    { key: "intro", anchor: null },
    { key: "editor", anchor: ADMIN_TOUR_ANCHORS.blogEditorRoot },
    { key: "titleField", anchor: ADMIN_TOUR_ANCHORS.blogEditorTitle },
    { key: "body", anchor: ADMIN_TOUR_ANCHORS.blogEditorBody },
    { key: "meta", anchor: ADMIN_TOUR_ANCHORS.blogEditorMeta },
    { key: "save", anchor: ADMIN_TOUR_ANCHORS.blogEditorSave },
    { key: "closing", anchor: null },
  ],
  "admin-blog-edit": [
    { key: "intro", anchor: null },
    { key: "editor", anchor: ADMIN_TOUR_ANCHORS.blogEditorRoot },
    { key: "titleField", anchor: ADMIN_TOUR_ANCHORS.blogEditorTitle },
    { key: "body", anchor: ADMIN_TOUR_ANCHORS.blogEditorBody },
    { key: "meta", anchor: ADMIN_TOUR_ANCHORS.blogEditorMeta },
    { key: "save", anchor: ADMIN_TOUR_ANCHORS.blogEditorSave },
    { key: "closing", anchor: null },
  ],
  "admin-glossary": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.glossaryTitle },
    { key: "hierarchy", anchor: ADMIN_TOUR_ANCHORS.glossaryHierarchy },
    { key: "groups", anchor: ADMIN_TOUR_ANCHORS.glossaryGroups },
    { key: "closing", anchor: null },
  ],
  "admin-analytics": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.analyticsTitle },
    { key: "traffic", anchor: ADMIN_TOUR_ANCHORS.analyticsTraffic },
    { key: "charts", anchor: ADMIN_TOUR_ANCHORS.analyticsCharts },
    { key: "closing", anchor: null },
  ],
  "admin-audit": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.auditTitle },
    { key: "toolbar", anchor: ADMIN_TOUR_ANCHORS.auditToolbar },
    { key: "table", anchor: ADMIN_TOUR_ANCHORS.auditTable },
    { key: "closing", anchor: null },
  ],
  "admin-cms": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.cmsTitle },
    { key: "templatesCard", anchor: ADMIN_TOUR_ANCHORS.cmsTemplatesCard },
    { key: "blogCard", anchor: ADMIN_TOUR_ANCHORS.cmsBlogCard, optional: true },
    { key: "closing", anchor: null },
  ],
  "admin-site-setup": [
    { key: "intro", anchor: null },
    { key: "stepIndicator", anchor: ADMIN_TOUR_ANCHORS.siteSetupStepIndicator },
    { key: "panel", anchor: ADMIN_TOUR_ANCHORS.siteSetupPanel },
    { key: "nav", anchor: ADMIN_TOUR_ANCHORS.siteSetupNav },
    { key: "closing", anchor: null },
  ],
  "admin-settings": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.settingsTitle },
    { key: "inscriptions", anchor: ADMIN_TOUR_ANCHORS.settingsInscriptions },
    { key: "classReminders", anchor: ADMIN_TOUR_ANCHORS.settingsClassReminders },
    { key: "blogTranslate", anchor: ADMIN_TOUR_ANCHORS.settingsBlogTranslate, optional: true },
    { key: "closing", anchor: null },
  ],
  "admin-settings-integrations": [
    { key: "intro", anchor: null },
    { key: "titleBlock", anchor: ADMIN_TOUR_ANCHORS.settingsIntegrationsTitle },
    { key: "form", anchor: ADMIN_TOUR_ANCHORS.settingsIntegrationsForm },
    { key: "save", anchor: ADMIN_TOUR_ANCHORS.settingsIntegrationsSave },
    { key: "closing", anchor: null },
  ],
  "admin-profile": [
    { key: "intro", anchor: null },
    { key: "header", anchor: ADMIN_TOUR_ANCHORS.profileHeader },
    { key: "avatar", anchor: ADMIN_TOUR_ANCHORS.profileAvatar },
    { key: "personalForm", anchor: ADMIN_TOUR_ANCHORS.profilePersonalForm },
    { key: "password", anchor: ADMIN_TOUR_ANCHORS.profilePassword, optional: true },
    { key: "closing", anchor: null },
  ],
} as const satisfies Record<string, readonly ContentOnlyStepDef[]>;
